{{- if not .Values.existingBonitaCredentialsSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-credentials" (include "bonita.fullname" .) | trunc 63 | trimSuffix "-" }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "bonita.labels" . | nindent 4 }}
type: Opaque
data:
  platform-password: {{ include "bonita.platformPassword" .  | b64enc | quote }}
  tenant-password: {{ include "bonita.tenantPassword" .  | b64enc | quote }}
  bonita-db-password: {{ include "bonita.bonitaDb.password" .  | b64enc | quote }}
  business-db-password: {{ include "bonita.businessDb.password" .  | b64enc | quote }}
{{- end }}