{{- if and (.Values.externalDatabase.enabled) (not .Values.externalDatabase.existingSecret) (not .Values.postgresql.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-externaldb" (include "bonita.fullname" .) | trunc 63 | trimSuffix "-" }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "bonita.labels" . | nindent 4 }}
type: Opaque
data:
  postgresql-password: {{ .Values.externalDatabase.password | b64enc | quote }}
{{- end }}
